theme = "PaperMod"
baseURL = 'https://vmsmith.github.io/'
languageCode = 'en-us'
title = 'As We May Yet Think'

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 1

  [[menu.main]]
    name = "Log"
    url = "/log/"
    weight = 2

  [[menu.main]]
    name = "Architecture"
    url = "/architecture/"
    weight = 3

  [[menu.main]]
    name = "Decisions"
    url = "/decisions/"
    weight = 4

  [[menu.main]]
    identifier = "stray-voltage"
    name = "Stray Voltage"
    url = "/stray-voltage/"
    weight = 5

  [[menu.main]]
    name = "Search"
    url = "/search/"
    weight = 6

[params]
  disableHomeList = true
  fuseJs = true
  ShowSearch = true
  disableSpecial1stPost = true
  homeInfoParams = false
  showNavLinks = true

[params.search]
  enabled = true

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML", "RSS"]
