theme = "PaperMod"
baseURL = 'https://vmsmith.github.io/'
languageCode = 'en-us'
title = 'As We May Yet Think'

[menu]

  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 10

  [[menu.main]]
    name = "Log"
    url = "/log/"
    weight = 20

  [[menu.main]]
    name = "Architecture"
    url = "/architecture/"
    weight = 30

  [[menu.main]]
    name = "Decisions"
    url = "/decisions/"
    weight = 40

[params]
disableHomeList = true

